import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { Toaster } from "@/components/ui/toaster"
import SlideBar from "./components/slidebar";
import Header from "./components/header_home";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
     
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
             <div className="sm:px-3 md:px-6">
              <div className="flex min-h-screen w-full flex-col bg-muted/40">
                <SlideBar/>
                <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
                  <Header/> 
                  {children}
                </div>
              </div>
             </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
